# Generated by Django 4.2.7 on 2024-01-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': 'Course Categories'},
        ),
        migrations.AddField(
            model_name='course',
            name='mandatory',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
