# Generated by Django 4.2.7 on 2024-01-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_coursecategory_options_course_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
