# Generated by Django 4.2.7 on 2024-01-26 12:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_course_mandatory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='estimated_completion_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.CreateModel(
            name='UserEnrolledCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapters_completed', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(max_length=100)),
                ('chapter_url', models.CharField(max_length=200)),
                ('estimated_completion_time', models.TimeField(default=datetime.time(0, 0))),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('media_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mediatypes')),
            ],
        ),
        migrations.CreateModel(
            name='BookmarkedCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapters_completed', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
        ),
    ]
