# Generated by Django 4.2.7 on 2024-01-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mediatypes_course_estimated_completion_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatypes',
            name='media_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
