# Generated by Django 4.2.7 on 2024-01-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_mediatypes_media_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursechapter',
            name='chapter_number',
            field=models.IntegerField(max_length=500, null=True),
        ),
    ]
