# Generated by Django 4.2.7 on 2024-01-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_coursechapter_chapter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursechapter',
            name='chapter_number',
            field=models.IntegerField(null=True),
        ),
    ]
