# Generated by Django 4.2.7 on 2024-01-27 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_coursechapter_chapter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mandatory_completion_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
