# Generated by Django 4.2.7 on 2024-01-30 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_course_mandatory_completion_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('answer', models.TextField()),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
