# Generated by Django 4.2.7 on 2024-02-14 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_remove_employee_date_created_remove_employee_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenrolledcourses',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
