# Generated by Django 4.2.7 on 2024-02-22 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_course_course_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_image_url',
        ),
    ]
