# Generated by Django 4.2.7 on 2024-02-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_course_course_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
