# Generated by Django 4.2.7 on 2024-02-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_employee_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_instructor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
