# Generated by Django 4.2.7 on 2024-03-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_employee_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
